spring:
  application:
     name: zuul-service

server:
  port: 8762
  
zuul:
  routes:
    tienda:
      path: /tienda/**
      serviceId: ms-tienda
      
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

