spring:
  application:
     name: ms-tienda
     
server:
  port: 5555


eureka:
  client:
    serviceUrl:
     defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    #instance:
      #preferIpAddress: true 
      
